server:
  port: 8090
spring:
  data:
    mongodb:
      username: admin
      password: password123
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin